Repository Grouping-Operators/foodtruckforager, pull requests merged in 2020-09, with the labels that each got.

#52 google sign in functional, .env file, route placeholders
  .gitignore
  App.tsx
  GoogleSignIn.tsx
  babel.config.js
  package-lock.json
  package.json
  server/index.js
  server/routes/auth.js
  server/routes/photo.js
  server/routes/truck.js
  server/routes/user.js
Labels: back-end, front-end

#54 added logout button/client folder/env variables
  App.tsx
  client/app.json
  client/components/GoogleLogIn.tsx
  client/tsconfig.json
  server/db/db.js
  server/routes/truck.js
Labels: back-end, front-end

#56 fleshed out truck routes
  .gitignore
  client/components/GoogleLogIn.tsx
  server/db/db.js
  server/db/models/Photo.js
  server/index.js
  server/routes/photo.js
  server/routes/truck.js
Labels: back-end

#57 finished truck routes/tested
  server/routes/truck.js
  server/routes/user.js
Labels: back-end

#58 Burger menu
  App.tsx
  client/components/dropIns/GoogleLogIn.tsx
  client/components/dropIns/header.tsx
  client/components/routes/drawer.tsx
  client/components/routes/loginStack.tsx
  client/components/routes/trackerStack.tsx
  client/components/screens/logIn.tsx
  client/components/screens/profile.tsx
  client/components/screens/search.tsx
  client/components/screens/searchResults.tsx
  client/components/screens/tracker.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckOwnerProfile.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
  package-lock.json
  package.json
Labels: front-end, good first issue

#61 (add) Accordion Layout for Profile
  client/Accordion/Accordion.tsx
  client/Accordion/Badges.tsx
  client/Accordion/Chevron.tsx
  client/Accordion/FavoriteTruck.tsx
  client/Accordion/ListItem.tsx
  client/Accordion/Settings.tsx
  client/Accordion/UserPosts.tsx
  client/Accordion/index.ts
  client/components/routes/drawer.tsx
  package-lock.json
  package.json
  server/routes/user.js
Labels: front-end, good first issue

#62 (add) User routes, Upvote Join Table
  server/db/database.sql
  server/db/db.js
  server/db/models/Upvote.js
  server/db/models/User.js
  server/routes/truck.js
  server/routes/user.js
Labels: back-end

#63 (fix) added json filetype functionality to badge in datatype
  server/db/db.js
  server/db/models/User.js
  server/routes/user.js
Labels: back-end

#65 (add) travis, test file, env var, tested routes
  package.json
  server/db/db.js
  server/index.js
  server/routes/auth.js
  server/routes/truck.js
  server/routes/user.js
  server/test/test.js
  travis.yml
Labels: back-end

#66 (documentation) added initial draft of README
  README.md
Labels: documentation

#69 (add) Initial map on tracker page, sample data from API call, custom callouts component started
  App.tsx
  client/components/constants/Colors.ts
  client/components/constants/Layout.ts
  client/components/dropIns/CustomCallout.tsx
  client/components/dropIns/Map.tsx
  client/components/hooks/useColorScheme.ts
  client/components/hooks/useColorScheme.web.ts
  client/components/hooks/usedCachedResources.ts
  client/components/screens/logIn.tsx
  client/components/screens/tracker.tsx
  client/components/themes/EditScreenInfo.tsx
  client/components/themes/StyledText.tsx
  client/components/themes/Themed.tsx
  client/data/googlePlacesSampleData.json
  client/data/yelpSampleData.json
  package-lock.json
  package.json
Labels: front-end

#70 (add) modular InfoWindow and Thumbnail drop-ins
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/Map.tsx
  client/components/dropIns/Thumbnail.tsx
Labels: front-end

#71 (add) Added rough search results page
  client/Accordion/Accordion.tsx
  client/components/screens/search.tsx
  client/components/screens/searchResults.tsx
  package-lock.json
  package.json
  server/routes/truck.js
Labels: front-end, good first issue

#72 (add) mapping markers to map
  client/components/dropIns/CustomCallout.tsx
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/Map.tsx
  server/routes/truck.js
  server/test/test.js
Labels: front-end

#73 (fix) database test now adds 3 trucks with all columns populated, (add) Added star ratings to InfoWindows
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/Thumbnail.tsx
  package-lock.json
  package.json
  server/test/test.js
Labels: enhancement, front-end, test

#74 (fix) Using axios to get trucks in useEffect, changed test command to…
  README.md
  client/components/dropIns/Map.tsx
  package-lock.json
  package.json
Labels: front-end

#75 (add) updated test file, updated infoWindow layout
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/Map.tsx
  client/components/dropIns/Thumbnail.tsx
  server/db/models/Review.js
  server/db/models/Truck.js
  server/test/test.js
Labels: back-end, front-end

#76 (fix) rerouted tracker button to search instead of search results
  client/components/screens/tracker.tsx
Labels: bug, front-end

#77 (fix) for app crash on empty search criteria
  client/components/screens/search.tsx
Labels: bug, front-end

#78 (add) added food genre search functionality to map tracker page
  client/components/dropIns/Map.tsx
  client/components/dropIns/MapSearch.tsx
  client/components/screens/tracker.tsx
Labels: front-end

#79 (fix) added more trucks to database test, fixed truck model to take p…
  server/db/models/Truck.js
  server/test/test.js
Labels: back-end, bug

#80 (enhancement) visual augmentations to search bar on main map screen
  client/components/dropIns/MapSearch.tsx
  package-lock.json
  package.json
Labels: enhancement, front-end

#81 (add) food-genre specific icons for markers on map
  client/components/dropIns/Map.tsx
  server/test/test.js
Labels: enhancement, front-end

#82 (fix) search is more responsive
  assets/mapIcons.js
  client/components/dropIns/Map.tsx
Labels: enhancement, front-end

#84 (fix) google login brings users to map page, brings truck owners to truck profile, (still has bugs)
  App.tsx
  client/components/dropIns/GoogleLogIn.tsx
  client/components/dropIns/Map.tsx
  client/components/routes/drawer.tsx
  client/components/screens/truckOwnerProfile.tsx
Labels: front-end

#83 (add) added fuzzy search capability for map search bar, can search by…
  client/components/dropIns/Map.tsx
  server/routes/truck.js
Labels: front-end

#85 (fix) test no longer produce duplicate trucks, added search by upper …
  client/components/dropIns/MapSearch.tsx
  server/routes/truck.js
  server/test/test.js
Labels: back-end

#86 (fix) added fuzzysearch for food genre and truck name
  client/components/dropIns/Map.tsx
  server/routes/truck.js
Labels: enhancement, front-end

#87 (fix) login more functional, logout still needs work
  App.tsx
  babel.config.js
  client/components/dropIns/GoogleLogIn.tsx
  client/components/routes/drawer.tsx
  client/components/routes/loginStack.tsx
  client/components/screens/LogIn.tsx
  client/components/screens/logIn.tsx
  server/routes/truck.js
  server/routes/user.js
Labels: front-end

#88 (fix) fuzzy name/foodgenre search more responsive and accurate, updat…
  client/components/dropIns/Map.tsx
  package-lock.json
  package.json
Labels: front-end

#89 (add) Added push notification capability
  App.tsx
  client/components/dropIns/PushNotifications.tsx
  client/components/screens/LogIn.tsx
Labels: enhancement, front-end

#90 (add) added routes to favorites/remove favorite trucks, added favorites table
  client/components/dropIns/GoogleLogIn.tsx
  client/components/dropIns/InfoWindow.tsx
  client/components/routes/drawer.tsx
  client/components/screens/LogIn.tsx
  client/components/screens/LogOut.tsx
  package-lock.json
  package.json
  server/db/db.js
  server/db/models/Favorite.js
  server/db/models/Review.js
  server/routes/user.js
Labels: back-end

#91 (add) Scan and Generate QR Codes
  assets/foodtruckstill.png
  assets/foodtruckstill256.png
  client/components/routes/drawer.tsx
  client/components/screens/GenerateQRCode.tsx
  client/components/screens/ScanQRCode.tsx
  package-lock.json
  package.json
Labels: enhancement, front-end

#92 (add) added get all favorite trucks route, created associations
  package-lock.json
  package.json
  server/db/db.js
  server/routes/user.js
Labels: back-end

#93 (add) User Geolocation enabled, user is shown on map and map zooms in to their location
  client/components/dropIns/Map.tsx
Labels: enhancement, front-end

#95 "(add) Profile Skeleton"
  client/components/screens/profile.tsx
  package.json
Labels: front-end, good first issue

#96 (add) added asyncStorage capability for userInfo
  client/components/dropIns/GoogleLogIn.tsx
  client/components/screens/LogOut.tsx
Labels: front-end

#97 Google Places and Google Geocode API call made for each truck
  client/components/dropIns/Map.tsx
  server/routes/truck.js
Labels: back-end, front-end

#98 (update) Info window
  client/components/dropIns/InfoWindow.tsx
  client/components/routes/drawer.tsx
  server/db/database.sql
  server/db/models/Truck.js
  server/test/test.js
  show
Labels: back-end, front-end

#99 Google places on map
  assets/foodtruckstill86.png
  assets/foodtruckstillsmall.png
  assets/mapIcons.js
  client/components/dropIns/Map.tsx
  server/routes/truck.js
Labels: back-end, front-end

#100 (fix) User location follow fix - only goes to location initially
  client/components/dropIns/Map.tsx
  server/routes/truck.js
Labels: front-end

#101 (fix) login/logout done
  client/components/dropIns/GoogleLogIn.tsx
  client/components/routes/drawer.tsx
  client/components/screens/LogIn.tsx
  client/components/screens/LogOut.tsx
Labels: front-end

#103 (add) made infowindow clickable to always route to truck details page
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/Map.tsx
  client/components/screens/tracker.tsx
  client/components/screens/truckDetails.tsx
Labels: front-end

#105 (fix) updated appearance to truck details page
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/Map.tsx
  client/components/screens/truckDetails.tsx
  server/routes/user.js
Labels: front-end

#106 (add) added map on truck details page
  client/components/dropIns/Map.tsx
  client/components/screens/truckDetails.tsx
  server/routes/truck.js
Labels: front-end

#107 (update) current truck now accessible on truckPosts and truckReviews …
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#108 (fix) fix for truck route tabs
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#109 (in progress) added to seed db file posts/reviews
  client/components/dropIns/TruckPostItem.tsx
  client/components/screens/truckPosts.tsx
  server/routes/user.js
  server/test/test.js
Labels: front-end

#110 (add) review page now shows first review
  client/components/screens/truckReviews.tsx
  server/test/test.js
Labels: front-end

#111 (add) Cloudinary / Upload new photo
  client/components/screens/settings.tsx
  package-lock.json
  package.json
  server/routes/user.js
Labels: front-end, good first issue

#112 (add) truck post page rendering truck post data
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/TruckPostItem.tsx
  client/components/screens/truckPosts.tsx
  server/test/test.js
Labels: front-end

#113 (fix) thumbnail loading spinner, fix for routing between details, pos…
  client/components/dropIns/InfoWindow.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#114 (cleanup) Login
  client/components/dropIns/GoogleLogIn.tsx
  client/components/dropIns/Map.tsx
  client/components/dropIns/header.tsx
  client/components/routes/trackerStack.tsx
  package-lock.json
  server/test/test.js
Labels: front-end

#115 (add) adding style to post screen
  client/components/dropIns/Thumbnail.tsx
  client/components/dropIns/TruckPostItem.tsx
  client/components/screens/truckPosts.tsx
Labels: front-end

#116 (Cleanup) InfoWindow
  client/components/dropIns/header.tsx
  client/components/routes/trackerStack.tsx
  client/components/screens/truckDetails.tsx
Labels: front-end

#121 (add) review date to schema, default user profile icon
  assets/mapIcons.js
  server/db/models/Review.js
Labels: back-end, front-end

#122 (add) truck review page displays first review
  client/components/screens/TruckReviewItem.tsx
  client/components/screens/truckReviews.tsx
  server/test/test.js
Labels: front-end

#123 (fix) truck review item in correct directory
  client/components/dropIns/TruckReviewItem.tsx
Labels: front-end

#124 (add) added review date to review posts page
  client/components/dropIns/TruckReviewItem.tsx
Labels: front-end

#125 (add) added preliminary TensorFlow.js & COCO-SSD library for machine …
  client/components/routes/drawer.tsx
  client/components/screens/ImageUpload.tsx
  package-lock.json
  package.json
Labels: front-end

#126 (add) truck owner registering on google login, routing to either profile or create/edit page
  client/components/dropIns/GoogleLogIn.tsx
  client/components/screens/LogIn.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  client/components/screens/TruckOwnerRouter.tsx
  client/components/screens/truckOwnerProfile.tsx
  package-lock.json
  package.json
  server/db/models/Truck.js
  server/routes/truck.js
Labels: front-end

#127 (fix) fixed bug, forgot to rename truck name back to full_name
  client/components/dropIns/GoogleLogIn.tsx
  client/components/screens/LogIn.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  client/components/screens/TruckOwnerRouter.tsx
  server/routes/truck.js
Labels: front-end

#128 Post review ui
  client/components/dropIns/SubmitOverlay.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#129 (add) users can create reviews for trucks
  client/components/dropIns/SubmitOverlay.tsx
  client/components/screens/truckReviews.tsx
  server/routes/user.js
  server/test/test.js
Labels: back-end, front-end

#130 (fix) reviews refresh on post
  client/components/dropIns/GoogleLogIn.tsx
  client/components/dropIns/SubmitOverlay.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#132 (add) trucks can now post their own messages
  assets/images/icon.png
  client/components/dropIns/SubmitOverlay.tsx
  client/components/dropIns/TruckPostItem.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
  server/db/models/Post.js
  server/db/models/Truck.js
Labels: back-end, front-end

#133 (add) fixed button group for truck reviews, details, posts
  client/components/dropIns/InfoWindow.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#134 (fix) header button fix on truck details/post/reviews so you can see …
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#135 (in progress) workingon routing from account creation to owner profile
  client/components/dropIns/GoogleLogIn.tsx
  client/components/routes/OwnerCreateProfileFirstStack.tsx
  client/components/routes/OwnerProfileFirstStack.tsx
  client/components/routes/drawer.tsx
  client/components/screens/LogIn.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  client/components/screens/TruckOwnerRouter.tsx
  package-lock.json
  package.json
Labels: front-end

#136 (Add) owner profile rendering data and updating on edit
  client/components/routes/OwnerCreateProfileFirstStack.tsx
  client/components/routes/OwnerProfileFirstStack.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
Labels: front-end

#137 (fix) No longer generating duplicate users after changing photo
  client/components/screens/settings.tsx
  server/routes/user.js
Labels: front-end

#140 (in progress) working on conditional render header for edit page
  client/components/routes/OwnerCreateProfileFirstStack.tsx
  client/components/routes/OwnerProfileFirstStack.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  server/db/models/Truck.js
Labels: front-end

#141 Truck owner location settings map
  client/components/dropIns/LocationSelectMap.tsx
  client/components/screens/TruckOwnerProfile.tsx
Labels: front-end

#142 (add) dragging marker pin on truck profile map updates truck location
  client/components/dropIns/LocationSelectMap.tsx
  client/components/screens/TruckOwnerProfile.tsx
  server/routes/truck.js
Labels: back-end, front-end

#144 (fix) truck location update from settings to database fix
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/truckPosts.tsx
Labels: back-end, front-end

#145 (fix) truck profile/edit routing correctly
  client/components/routes/OwnerCreateProfileFirstStack.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  server/routes/user.js
Labels: front-end

#146 (add) User favorite truck
  client/components/dropIns/InfoWindow.tsx
  client/components/screens/truckDetails.tsx
  package-lock.json
  package.json
  server/routes/user.js
Labels: back-end, front-end

#147 (add) owner profile page almost done, added drop down for blurb, rendering all data except stars and reviews
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/TruckReviewItem.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  package-lock.json
  package.json
Labels: front-end

#148 (add) Users can favorite trucks and those show up in their profile
  client/Accordion/Accordion.tsx
  server/routes/user.js
Labels: front-end

#149 (fix) infowindow fix
  client/components/dropIns/InfoWindow.tsx
Labels: front-end

#150 (fix) readme updates to env variables, header logo
  README.md
Labels: documentation

#155 (fix) fixing user profile
  client/Accordion/Accordion.tsx
  client/components/routes/OwnerProfileFirstStack.tsx
  client/components/routes/drawer.tsx
  client/components/screens/settings.tsx
Labels: front-end

#156 (in progress) making qr code functional
  client/components/routes/OwnerCreateProfileFirstStack.tsx
  client/components/routes/drawer.tsx
  client/components/screens/GenerateQRCode.tsx
  client/components/screens/ScanQRCode.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  package-lock.json
  package.json
  server/db/db.js
  server/db/models/User.js
  server/db/models/Vists.js
  server/routes/user.js
  server/test/test.js
Labels: back-end, front-end

#157 (in progress) working on badges, 2 badges done, hitting server, saving
  client/Accordion/Accordion.tsx
  server/routes/user.js
Labels: back-end, front-end

#158 (in progress) 5/6 achievements done
  client/Accordion/Accordion.tsx
  server/db/models/User.js
Labels: front-end

#159 (add) made all buttons round, fixed styling in profile
  client/components/dropIns/GoogleLogIn.tsx
  client/components/dropIns/SubmitOverlay.tsx
  client/components/screens/GenerateQRCode.tsx
  client/components/screens/TruckOwnerProfile.tsx
Labels: front-end

#160 (add) adding tentative if block check for if user has earned "The Reg…
  client/Accordion/Accordion.tsx
Labels: front-end

#162 (add) started off user settings modal
  README.md
  client/Accordion/Accordion.tsx
  client/components/dropIns/GoogleLogIn.tsx
  client/components/dropIns/UserProfileSettingsOverlay.tsx
  client/components/dropIns/header.tsx
  client/components/screens/settings.tsx
Labels: front-end

#163 (fix) centered user profile name
  client/Accordion/Accordion.tsx
  client/components/dropIns/UserProfileSettingsOverlay.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  client/components/screens/settings.tsx
Labels: front-end

#164 (fix) updated header done, removed truck logo
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/header.tsx
  client/components/routes/trackerStack.tsx
  client/components/screens/tracker.tsx
  client/components/screens/truckDetails.tsx
Labels: front-end

#165 (add) Time picker user profile
  client/components/dropIns/UserProfileSettingsOverlay.tsx
  client/components/screens/truckDetails.tsx
  package-lock.json
  package.json
Labels: front-end

#166 (add) posts and reviews are now more aesthetic
  client/components/dropIns/TruckPostItem.tsx
  client/components/dropIns/TruckReviewItem.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#167 (fix) review-detail-post-header-button-fix
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
Labels: front-end

#168 (fix) truck details page done, added card, repositioned map
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/SubmitOverlay.tsx
  client/components/screens/truckDetails.tsx
  server/test/test.js
Labels: front-end

#169 (fix) fixed it so new favorites show up without
  client/Accordion/Accordion.tsx
  server/test/test.js
Labels: front-end

#170 (fix) info-window-post-review-details-fix for aesthetics and visibility
  client/components/dropIns/InfoWindow.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#183 (fix) expo permissions and notifications along with expo-cli update
  package-lock.json
  package.json
Labels: back-end, front-end

#185 (fix) removed async storage call in truck router, fixed switch colors
  client/components/dropIns/GoogleLogIn.tsx
  client/components/dropIns/UserProfileSettingsOverlay.tsx
  client/components/screens/LogIn.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  client/components/screens/TruckOwnerRouter.tsx
  server/routes/truck.js
Labels: front-end
